---
# Source: sample-java-app-metric-samples/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sample-java-app-metric-samples
subjects:
  - kind: ServiceAccount
    name: sample-java-app-metric-samples
roleRef:
  kind: Role
  name: sample-java-app-metric-samples
  apiGroup: rbac.authorization.k8s.io