resources:
 - ../../base/sample-java-app-qm01
 # - queuemanager/hooks/post-sync-job.yaml
 # - certificates/dev-sample-java-app-client-certificate.yaml
 # - certificates/dev-sample-java-app-server-certificate.yaml
 # - secrets/sample-java-app-client-jks-password-secret.yaml

# Add the configMap that will be used for dynamic updates, this should be used queue manager wide i.e. stay the same in each environment.
components:
- components/dynamic-sample-java-appsc/generic-qmgr
- components/scripts

generatorOptions:
 disableNameSuffixHash: true
# We use a configMapGenerator because it allows us to build up the sample-java-appsc from regular sample-java-appSC files.
configMapGenerator:
# Create an sample-java-appSC configMap using generic sample-java-appSC which will be added to all queue managers and applied during bootstrap.
- name: sample-java-appsc-configmap
  behavior: create
  files:
  - configmap/static-definitions.sample-java-appsc
patchesStrategicMerge:
 - queuemanager/queuemanager.yaml
 - components/dynamic-sample-java-appsc/generic-qmgr/queuemanager.yaml
