apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgCB/ZUk58nFTSMt9fJMfF0+e3cWacBQ604q72BLFf7Aa5eLbWaLCcL49td2c5gXAwQMfOWy0Uo9CayIXwX7LNJ0jaoDgiFc4oFZYjFYnPYH82FSEfBiniBy97C2vBC4EmxMpoUpIvLwxAMwkZyh/ulaH6fXn+Qigk7u2h3Joksample-java-app5gO2ZYbqOqA5ENwKAbx6o3Wk/UwxvHMrjlMtNQaszp+jmLDvExSWK6ljxUgSgWyKYDRn6BbjjitMcNzIhVxObcMmJOA9Hq9R1AYLg0TlNMS5nDSAWo1+w2W/X/OAreXb4PMTVlnFfr6MhI8fwJSUysoR13nWdvODgCwtOo+pFQHoXDoSG8ZtBd98ovW7Y0w6S3ZDJ0sMcttEw07jjEBJnNjMwXrtf/OzgGPSZAPCv54JLUBRaG/TPj66UM+ft9FbvWWTeHPOm30wM80qrR6cW8+9gtXOgsrin7O59Nnv1DB8X05jcSQqRP7c9QUTWkxVazLAjkW8zzNznBSZH5idLFgEck+QDngjSyEPQPjGMJhlJrFOkZUlLoecu/f7x9JNJD9vN7tpukb1v9rnNRoWOonj7bs7zxZ4fU5UdDhnTe+XXF2dgKft+tqi247SIzeLh3GkQoQGtvCiDcaovUL8In3kCiTdVKlonFVANKij6Ps6lmgGG0YkJVmUHJGZG80bP5lUOEb0ox5rXvDamCWPKjoHDLqQpDk4kkWFUsTuOaEDi+8N3HyL7WJUe+Vquq6BcMee+3xjszSL
    username: AgAqSOw6kMOKg53u/F7mpiz40h4oFenz6gegiy478NVv8v5gyY42Ltc3wTs+ML1fq4iwpkqlti3xs33Lbhu1skf0IR6bEI/LLadU4fuBI71WFp+sG8/s/tLlX9i1gGdkwx53N9f3ZrsR6fLz/C7jBwMhYDLd7A7DSODL0oYCuuniY4JymNTteWAx8prAix9k/SdegkAqJSlLIC1O86IkZ0iJOVFZ+NabHGhodjpMCJHoKSHeW7vS3CkQ0ksN5PwcdVgFOh1gfbxB5vM65VJ/XqjU/NBmtsu6161mYPBr/HI+e8AwwMuUVLztHfh09c/2LKhC0/JdUfu7P2A7TfSwMJdWWcEcnldMvqy+rWwYN8byUNIfXCuzUS5H24whHaxUNURB/VHYR67MxJrV5EssL4Ew+tVmt9jzdSyamHyH61ALtyF1NWNrssBDeCmWugcLg+PMa3UFtlsDyKSoQvlXGs9Ww8ypx+F6XZrSyHSGwS/jvPbhkjufHcJbs7rTAMYP5oCQrWmUwPaDARUPUYBxNm3WkUdYRW1PpOb6kWPNNBU41GlHRq3msample-java-applIpsIemL5+gRMwbONO8OJXrfXdlTgkhgjQIESSV9ib7yoCsN729qzBu7LHUbZipf522O+Nbixj2gsUpp/EtppBIiSqH59HRBWrO5Ak2txLB19tf+iNGZjKGw0f+O43cTki1WIwgpxIchBwbar7R4VhvJo=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

