apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBrv42o0qfrB62HTWhpfDrzMs2XXDlCfR0J7+4YjSH4f572S2pmB8PDgYXmDM3N0FFSa4BGwWzqYP23Wa5OvosKc/E2FulklFwMCdu+zZXpg6xCNsTs9t/jgXpNmA9vKJFhP+k/FWjImKvKgRsUmkB4v7CT1yjSp6clt/Lcv8bpQVGhBfo7iDrNwIbgCm3t2AvqlDaTV4OQtNSIZ+ejONuHqxQ7PEiRS9OLkM606txCMNnVBbTX0cU3lTQxf9M3POPd3J00Quo1rvlNQjFzVbOfF1YkyfoQnzhhE16Q6Ynjf6YRohaOWf1KcTbtqj+Eic3P7y9hhb1JsXHbBWBn1vichlj2ugmC+XzVt9dUUdvPzEUJsxDr4vgs/tYHMZvtLi7U7R1c0/r9GQw7p3cPOtpFemxOj/OBwNPPFx0qIL5bUjgIJ4zmWOB0havqOpsjz3tQznZIdgY/W+SV+2Gyuz9o08qSsNbD8PVFmKUXWaRqtEcVgR3HEPFxUiAbJOftsample-java-appB/TpPp0K65GjljZkSGnc5RfLDf1jDMVZCKM+jdWlKlq1x5q4stlSksUSQCk4dBGdSShWQnK/SojArMxHsquOatAkp/5jyboYwVp0XvVymOzzpKEIGpm9E2S+vZXIzEmj3TvzqEbYhHKZfPciyGu0TKz8ZlOjTqzlaoTokpPQAJDLQNiaQuI4msNruKTpxAmzTqu8cv/b0XSiTv4I/PzUay5dUMjCCwQ8FBfGmuL+ZqCVziaCXXxN2Ovuw2E1EvqXj8yIMx52r5zGwl5lNXeYaG7O7npaeEc6Tj8ff5Xs22woEJ3r5puO+UNd9Uf+G5W6dfpE55RUARRb2S3j9GhnLkD0zHFhXvkd6umwE8PTUMHGcEv/u0bXdZnrLkCeknVWcKKXd1nuI9AAY8jDOdX+sample-java-app8EFyhHeQwt2o5xiM6jxl8kbbD18q+nEYBTjX/VjUwwU=
    IBM_ENTITLED_REGISTRY_USER: AgCLK4SKr/uq5CX9ti4gL4qz7KyBFabeKmGiW1XmxCft8zr3Yq7sample-java-appBoygp4Jw9IoYlRwOFVT7dB5SE4rLh8MazZHKdZSYn9MscNKtHn3qPIsi/iWtNH4p9CyMUXD0ws6WSDuwh5Aj9KLmVYGsqYNo3K9sRvWinWwqt1O2Ha1NZD40CDY1X6DFqZCGQMK61PBnhN9SHOGIW6XWUT7QZiguNwYBmcmEMIzpHo2gEvLscySOU9S5FfQBlYzvLg1/MoieMS+Wd16HBjS5bMGNtcrBMAWsCsUH90yFCVqf7ll4oKVmuhEV2IMZgqE8KjLfbs6OEIDbNPPqYn8wQfe5ky9Uo8w2M7G1/uMN3pIRink0ixvxOaF9I40si9jRwbhH/2B1RnRb6882VbTJTPorP8TBlYk/v/Q2P67dvyoX+EfqA7+SIG4PpgVrAOeZR5RYhxImt43nMFTsIdKz+dVZV7OKIHuPYxnuYUX3thEJKvk7mPyLNFcpeXbIJxZo1dxZdmFHUT3ykfPo3xcDH7zCZxQVwbce5cc0RfToKEOnPPc37Z1qCyV4G/KJhgGkFNg0/u56eT1tUgM9g1zHhHo8g1kXmKkiahKOSzTuB4Zzg8+H5qMSfE7KZIsFU87YHjK0PQV99GjgWCVeWPjqq7D5zEYYsIO92KtEJucR1eiypOdTLlSxC0VSfvDidvW9DtW0Ndmo/hrKA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

