apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
 disableNameSuffixHash: true

# Create a configMap that will be used with a volume that is dynamically updated.
configMapGenerator:
- name: dynamic-sample-java-appsc-configmap
  behavior: create
  files:
  - dynamic-definitions.sample-java-appsc

patchesStrategicMerge:
  - ./queuemanager.yaml
