# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-started-java
  labels:
    app: get-started-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-started-java
  template:
    metadata:
      labels:
        app: get-started-java
    spec:
      containers:
      - name: get-started-java
        image: "image-registry.openshift-image-registry.svc:5000/ci/sample-java-app:0.0.2"
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true


