apiVersion: sample-java-app.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: qm1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    helm.sh/hook-weight: "300"
spec:
  template:
    pod:
      volumes:
        - name: config-volume-scripts
          configMap:
            name: scripts-configmap
            defaultMode: 0777
        - name: dynamic-config-volume-sample-java-appsc
          configMap:
            name: dynamic-sample-java-appsc-configmap
            defaultMode: 0777
      containers:
        - env:
            - name: sample-java-appSNOAUT
              value: 'yes'
          name: qmgr
          volumeMounts:
          - name: config-volume-scripts
            mountPath: /sample-java-app-config
            readOnly: true
            #optional: true
          - name: dynamic-config-volume-sample-java-appsc
            mountPath: /dynamic-sample-java-app-config-sample-java-appsc
            readOnly: true
            #optional: true
