resources:
#- certificates/sample-java-app-selfsigned-certificate/sample-java-app-self-signed-ca-certificate.yaml
#- cluster-issuers/sample-java-app-selfsigned-clusterissuer/sample-java-app-self-signed-clusterissuer.yaml
#- cluster-issuers/selfsigned-clusterissuer/clusterissuer.yaml