apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: sample-java-app-post-stage
spec:
  serviceAccountName: pipeline
  triggers:
    - name: sample-java-app-post-stage
      template:
        ref: sample-java-app-post-stage
